# Generated by Django 3.0.5 on 2020-06-14 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('common_func', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebSEO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('keywords', models.TextField(blank=True, max_length=70, verbose_name='关键字')),
                ('brief', models.CharField(blank=True, max_length=70, verbose_name='简介')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contenttypes.ContentType')),
            ],
        ),
    ]
