# Generated by Django 3.0.5 on 2020-05-17 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200518_0220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='caregory',
            new_name='category',
        ),
    ]
