# Generated by Django 3.0.5 on 2020-05-30 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200521_0151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_time'], 'verbose_name_plural': '文章'},
        ),
    ]
