# Generated by Django 3.0.5 on 2020-06-04 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_article_read_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='read_num',
        ),
        migrations.CreateModel(
            name='Read_num',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_num', models.IntegerField(default=0, verbose_name='阅读次数')),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='blog.Article')),
            ],
        ),
    ]
