# Generated by Django 3.0.5 on 2020-06-04 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200604_2326'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Read_num',
            new_name='Readnum',
        ),
    ]
