# Generated by Django 3.0.5 on 2020-06-04 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20200605_0101'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Readnum',
        ),
    ]
