# Generated by Django 3.1 on 2020-05-18 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('architecture', '0003_auto_20200518_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='architecture',
            name='architect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='architecture.architect'),
        ),
        migrations.AlterField(
            model_name='architecture',
            name='build_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='architecture.country'),
        ),
        migrations.AlterField(
            model_name='architecture',
            name='build_time',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='architecture',
            name='structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='architecture.structure'),
        ),
    ]
