# Generated by Django 3.1 on 2020-05-18 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('architecture', '0004_auto_20200518_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='architect',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='img_architect'),
        ),
    ]
